version: "3.1"
services:
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - './data/mongo:/data/db'
    ports:
      - "27017:27017"

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: elastic
    environment:
      - discovery.type=single-node
    volumes:
      - './data/elastic:/usr/share/elasticsearch/data'
    ports:
      - '9200:9200'
      - '9300:9300'