# Use the official image as a parent image.
FROM openvidu/openvidu-server-kms:2.14.0

# Set the working directory.
ENV OPENVIDU_SECRET=pioneer123
ENV DOMAIN_OR_PUBLIC_IP=192.168.1.17 

# Inform Docker that the container is listening on the specified port at runtime.
EXPOSE 4443:4443

